import Link from "next/link";
import { auth } from "@/auth";
import { ArrowRight, BookOpenText, Bot, BrainCircuit, Check, ChevronRight, Cpu, Feather, Layers3, Library, Network, PenLine, ShieldCheck, Sparkles, WandSparkles, Zap } from "lucide-react";
import { TypewriterText } from "@/components/typewriter-text";
import { getSiteSettings } from "@/lib/site-settings";

const features = [
  { icon: BrainCircuit, title: "先规划，再成书", text: "AI 先完成世界观、人物关系与章节节奏规划，再按章生成，长篇创作不再前后失忆。" },
  { icon: Layers3, title: "10–50 章完整结构", text: "每章拥有独立剧情目标和情节点，章节之间自动衔接，支持十万字以内的完整短篇小说。" },
  { icon: Network, title: "多模型智能调度", text: "默认模型与备用模型自动切换，调用失败不丢进度，价格和倍率均由管理员集中配置。" },
  { icon: Library, title: "作品级阅读体验", text: "完成后自动进入书架，提供目录、上下章、夜间主题、字号调节和移动端断点续读。" },
  { icon: ShieldCheck, title: "私有创作空间", text: "小说、模板和生成记录按用户严格隔离，创意素材只属于创作者本人。" },
  { icon: Cpu, title: "透明 Token 计费", text: "按模型真实输入与输出 Token、官方价格及费率倍率扣除算力点，每笔消耗都有流水。" },
];
const genres = ["反转悬疑", "都市情感", "科幻脑洞", "古风言情", "无限流", "现实题材", "恐怖惊悚", "温情治愈", "奇幻冒险", "职场商战"];

export default async function Home() {
  const [session, settings] = await Promise.all([auth(), getSiteSettings()]);
  const href = session?.user?.id ? "/projects" : "/register";
  return <main className="landing-grid min-h-screen overflow-hidden bg-[#f7f5f0] text-[#171717]">
    <header className="relative z-30 mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
      <Link href="/" className="flex items-center gap-3 font-serif text-xl font-semibold">{settings.logoUrl ? <img src={settings.logoUrl} alt={settings.siteName} className="size-10 rounded-xl object-contain shadow-lg" /> : <span className="grid size-10 place-items-center rounded-xl bg-[#171717] text-white shadow-lg"><BookOpenText className="size-5" /></span>}{settings.siteName} <span className="hidden border-l border-black/15 pl-3 font-sans text-xs font-normal tracking-[.22em] text-black/40 sm:inline">AI NOVEL STUDIO</span></Link>
      <div className="flex items-center gap-2">{session?.user?.id ? <Link className="landing-button-dark" href="/projects">进入工作台<ArrowRight className="size-4" /></Link> : <><Link className="hidden px-4 py-2 text-sm font-medium sm:block" href="/login">登录</Link><Link className="landing-button-dark" href="/register">免费开始<ArrowRight className="size-4" /></Link></>}</div>
    </header>

    <section className="relative mx-auto grid min-h-[760px] max-w-7xl items-center gap-12 px-5 pb-24 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-28 lg:pt-20">
      <div className="relative z-10">
        <div className="inline-flex items-center gap-2 rounded-full border border-black/10 bg-white/70 px-3 py-1.5 text-xs font-medium shadow-sm backdrop-blur"><Sparkles className="size-3.5 text-[#ff5b35]" />从一个灵感，到一部完整小说</div>
        <h1 className="mt-8 max-w-3xl font-serif text-[clamp(3.35rem,7vw,6.5rem)] font-semibold leading-[1.02] tracking-[-.055em]">让故事拥有<TypewriterText /></h1>
        <p className="mt-8 max-w-xl text-base leading-8 text-black/55 sm:text-lg">{settings.siteName}是一间由 AI 驱动的小说创作工作室。从题材设定、大纲编排到逐章成稿，让 10–50 章、十万字以内的故事稳定落地。</p>
        <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href={href} className="landing-button-dark px-6 py-3.5 text-base">{session?.user?.id ? "继续我的创作" : "开始第一部小说"}<ArrowRight className="size-4" /></Link><a href="#workflow" className="inline-flex items-center justify-center gap-2 rounded-xl border border-black/15 bg-white/60 px-6 py-3.5 text-base font-medium backdrop-blur transition hover:bg-white">了解创作流程<ChevronRight className="size-4" /></a></div>
        <div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-xs text-black/45"><span className="flex items-center gap-2"><Check className="size-3.5 text-emerald-600" />完整章节大纲</span><span className="flex items-center gap-2"><Check className="size-3.5 text-emerald-600" />连续上下文</span><span className="flex items-center gap-2"><Check className="size-3.5 text-emerald-600" />随时继续生成</span></div>
      </div>
      <div className="relative mx-auto h-[500px] w-full max-w-[570px] sm:h-[580px]"><div className="landing-orbit absolute left-1/2 top-1/2 size-[440px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-black/10 sm:size-[520px]"><div className="absolute left-1/2 top-1/2 size-[320px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-dashed border-black/10 sm:size-[390px]" /><div className="absolute left-1/2 top-1/2 size-40 -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#ff5b35]/20 bg-[#ff5b35]/5 blur-2xl" /></div><div className="absolute left-1/2 top-1/2 grid size-32 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-[2rem] border border-white bg-[#171717] text-white shadow-[0_30px_80px_rgba(24,24,24,.28)] sm:size-40"><BrainCircuit className="size-14 sm:size-16" /><span className="absolute -bottom-8 text-[10px] font-semibold uppercase tracking-[.3em] text-black/35">Story Engine</span></div><div className="landing-float absolute left-0 top-14 w-48 rounded-2xl border border-black/10 bg-white/85 p-4 shadow-xl backdrop-blur"><div className="flex items-center gap-2 text-xs font-semibold"><span className="grid size-7 place-items-center rounded-lg bg-violet-50 text-violet-600"><Feather className="size-3.5" /></span>人物弧光</div><div className="mt-4 space-y-2"><div className="h-1.5 w-full rounded bg-black/10" /><div className="h-1.5 w-4/5 rounded bg-black/10" /><div className="h-1.5 w-3/5 rounded bg-[#ff5b35]/35" /></div></div><div className="landing-float-delay absolute right-0 top-24 w-48 rounded-2xl border border-black/10 bg-white/85 p-4 shadow-xl backdrop-blur"><div className="flex items-center justify-between"><span className="text-xs font-semibold">章节结构</span><span className="text-[10px] text-emerald-600">READY</span></div><div className="mt-4 grid grid-cols-5 gap-1.5">{Array.from({ length: 15 }, (_, i) => <span key={i} className={`h-5 rounded ${i < 11 ? "bg-[#171717]" : "bg-black/10"}`} />)}</div></div><div className="landing-float-delay absolute bottom-16 left-6 w-52 rounded-2xl border border-black/10 bg-white/90 p-4 shadow-xl backdrop-blur"><div className="flex items-center gap-2"><Bot className="size-4 text-[#ff5b35]" /><span className="text-xs font-semibold">AI 正在续写</span><span className="ml-auto flex gap-1"><i className="size-1 animate-pulse rounded-full bg-[#ff5b35]" /><i className="size-1 animate-pulse rounded-full bg-[#ff5b35] [animation-delay:.2s]" /><i className="size-1 animate-pulse rounded-full bg-[#ff5b35] [animation-delay:.4s]" /></span></div><p className="mt-3 font-serif text-sm leading-6 text-black/55">雨落在旧城的屋檐上，他终于读懂那封迟到了十年的信……</p></div><div className="landing-float absolute bottom-24 right-1 rounded-2xl border border-black/10 bg-[#171717] p-4 text-white shadow-xl"><div className="flex items-center gap-3"><Zap className="size-4 text-amber-300" /><div><p className="text-[10px] text-white/45">CONTEXT</p><p className="mt-0.5 text-sm font-semibold">128K 连续记忆</p></div></div></div></div>
    </section>

    <section className="border-y border-black/10 bg-white/60 backdrop-blur"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-black/10 px-5 sm:grid-cols-4 lg:px-8">{[["10–50", "章节精细规划"], ["100,000", "字以内完整成书"], ["2,000+", "每章目标字数"], ["24/7", "持续 AI 创作"]].map(([value, label]) => <div className="px-4 py-8 text-center" key={label}><p className="font-serif text-3xl font-semibold sm:text-4xl">{value}</p><p className="mt-2 text-xs text-black/40">{label}</p></div>)}</div></section>
    <section id="ability" className="mx-auto max-w-7xl px-5 py-28 lg:px-8"><div className="max-w-2xl"><p className="eyebrow">AI-native creation</p><h2 className="mt-4 font-serif text-4xl font-semibold tracking-tight sm:text-5xl">不是一次生成，<br />而是一套完整创作系统。</h2></div><div className="mt-14 grid gap-px overflow-hidden rounded-3xl border border-black/10 bg-black/10 md:grid-cols-2 lg:grid-cols-3">{features.map(({ icon: Icon, title, text }, index) => <article key={title} className="group bg-[#faf9f6] p-7 transition hover:bg-white sm:p-8"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-xl border border-black/10 bg-white shadow-sm transition group-hover:border-[#ff5b35]/30 group-hover:text-[#ff5b35]"><Icon className="size-5" /></span><span className="font-mono text-xs text-black/25">0{index + 1}</span></div><h3 className="mt-8 font-serif text-2xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-black/50">{text}</p></article>)}</div></section>
    <section id="workflow" className="relative overflow-hidden bg-[#171717] py-28 text-white"><div className="absolute inset-0 opacity-20 [background-image:linear-gradient(rgba(255,255,255,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.08)_1px,transparent_1px)] [background-size:64px_64px]" /><div className="relative mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#ff8062]">Four-step workflow</p><h2 className="mt-4 font-serif text-4xl font-semibold sm:text-5xl">四步，让灵感成为作品。</h2></div><p className="max-w-md text-sm leading-7 text-white/45">每一步都保留控制权。你决定题材、人物和方向，AI 负责结构化思考与持续执行。</p></div><div className="mt-16 grid gap-8 md:grid-cols-4">{[[PenLine, "01", "描述故事", "填写主题、主角、世界观、风格和预期字数。"], [WandSparkles, "02", "构建大纲", "生成完整人物关系、故事梗概与逐章剧情。"], [Cpu, "03", "逐章成稿", "依据大纲和前文上下文，稳定生成每一章节。"], [BookOpenText, "04", "阅读成书", "进入沉浸阅读器，目录、翻章和断点续读全部就绪。"]].map(([Icon, no, title, text]) => { const StepIcon = Icon as typeof PenLine; return <div key={String(no)} className="relative border-t border-white/15 pt-7"><span className="absolute -top-3 right-0 bg-[#171717] pl-3 font-mono text-xs text-white/30">{String(no)}</span><StepIcon className="size-6 text-[#ff8062]" /><h3 className="mt-6 font-serif text-xl font-semibold">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-white/40">{String(text)}</p></div>; })}</div></div></section>
    <section id="genres" className="mx-auto max-w-7xl px-5 py-28 lg:px-8"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow">Genres & templates</p><h2 className="mt-4 font-serif text-4xl font-semibold sm:text-5xl">每一种故事，<br />都有专属叙事逻辑。</h2><p className="mt-6 max-w-md text-sm leading-7 text-black/50">系统小说类型分别配置大纲 Prompt 与章节 Prompt。既能直接使用，也能复制后打造自己的创作方法。</p><Link href={href} className="mt-8 inline-flex items-center gap-2 text-sm font-semibold">探索小说工作台<ArrowRight className="size-4" /></Link></div><div className="relative flex min-h-80 flex-wrap content-center justify-center gap-3 rounded-[2rem] border border-black/10 bg-white/55 p-8 shadow-soft sm:p-12">{genres.map((genre, index) => <span key={genre} className={`rounded-full border px-5 py-3 text-sm shadow-sm ${index % 4 === 0 ? "border-[#ff5b35]/25 bg-[#ff5b35]/5 text-[#b83c1e]" : "border-black/10 bg-white text-black/60"}`}>{genre}</span>)}<span className="absolute left-6 top-6 size-2 rounded-full bg-[#ff5b35]" /><span className="absolute bottom-6 right-6 size-2 rounded-full bg-[#171717]" /></div></div></section>
    <section className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div className="relative overflow-hidden rounded-[2.25rem] bg-[#ff5b35] px-6 py-16 text-center text-white sm:px-12 sm:py-20"><div className="absolute inset-0 opacity-20 [background-image:radial-gradient(circle_at_center,white_1px,transparent_1px)] [background-size:22px_22px]" /><Sparkles className="relative mx-auto size-8" /><h2 className="relative mt-6 font-serif text-4xl font-semibold sm:text-5xl">你的下一部小说，从这里开始。</h2><p className="relative mx-auto mt-5 max-w-xl text-sm leading-7 text-white/75">不需要先成为 Prompt 专家。只需带着一个值得讲述的故事，其余交给章回。</p><Link href={href} className="relative mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3.5 font-semibold text-[#171717] shadow-xl">{session?.user?.id ? "返回工作台" : "免费创建账号"}<ArrowRight className="size-4" /></Link></div></section>
    <footer className="border-t border-black/10"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-xs text-black/40 sm:flex-row sm:items-center sm:justify-between lg:px-8"><span className="flex items-center gap-2 font-serif text-sm font-semibold text-black/65"><BookOpenText className="size-4" />{settings.siteName} AI 小说工作室</span><span>{settings.footerCopyright}</span></div></footer>
  </main>;
}
