"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { BookOpenText, ChevronLeft, ChevronRight, List, Minus, Moon, Plus, Settings2, Sun, X } from "lucide-react";
type Chapter = { number: number; title: string; content: string };
export function NovelReader({ project, chapters, initialChapter }: { project: { id: string; title: string }; chapters: Chapter[]; initialChapter: number }) {
  const [number, setNumber] = useState(initialChapter); const [catalog, setCatalog] = useState(false); const [settings, setSettings] = useState(false); const [fontSize, setFontSize] = useState(18); const [night, setNight] = useState(false); const [restored, setRestored] = useState(false);
  const chapter = chapters.find((item) => item.number === number) || chapters[0]; const progress = Math.round((chapter.number / chapters.length) * 100); const paragraphs = useMemo(() => chapter.content.split(/\n+/).map((item) => item.trim()).filter(Boolean), [chapter.content]);
  useEffect(() => {
    const savedFont = Number(localStorage.getItem("novel-reader-font"));
    const savedChapter = Number(localStorage.getItem(`novel-progress-${project.id}`));
    if (savedFont >= 15 && savedFont <= 24) setFontSize(savedFont);
    if (Number.isInteger(savedChapter) && savedChapter >= 1 && savedChapter <= chapters.length) setNumber(savedChapter);
    setNight(localStorage.getItem("novel-reader-night") === "1");
    setRestored(true);
  }, [chapters.length, project.id]);
  useEffect(() => { if (!restored) return; localStorage.setItem(`novel-progress-${project.id}`, String(number)); window.scrollTo({ top: 0, behavior: "smooth" }); history.replaceState(null, "", `/projects/${project.id}/read?chapter=${number}`); }, [number, project.id, restored]);
  function changeFont(next: number) { const value = Math.min(24, Math.max(15, next)); setFontSize(value); localStorage.setItem("novel-reader-font", String(value)); }
  function toggleNight() { setNight(!night); localStorage.setItem("novel-reader-night", night ? "0" : "1"); }
  return <div className={`fixed inset-0 z-[80] overflow-y-auto transition-colors ${night ? "bg-[#171717] text-[#d8d3ca]" : "bg-[#f4efe5] text-[#29241f]"}`}>
    <div className="fixed inset-x-0 top-0 z-20 h-1 bg-black/10"><div className="h-full bg-ember" style={{ width: `${progress}%` }}/></div>
    <header className={`sticky top-0 z-10 border-b backdrop-blur-xl ${night ? "border-white/10 bg-[#171717]/90" : "border-black/10 bg-[#f4efe5]/90"}`}><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-3 sm:px-6"><Link href="/projects" className="flex items-center gap-1.5 rounded-xl px-2 py-2 text-sm opacity-65 hover:opacity-100"><ChevronLeft className="size-4"/><span className="hidden sm:inline">返回书架</span></Link><div className="min-w-0 px-2 text-center"><p className="max-w-[45vw] truncate font-serif font-semibold">{project.title}</p><p className="text-[11px] opacity-45">{chapter.number}/{chapters.length} · {progress}%</p></div><div className="flex"><button aria-label="目录" className="rounded-xl p-2.5 hover:bg-black/5" onClick={() => setCatalog(true)}><List className="size-5"/></button><button aria-label="阅读设置" className="rounded-xl p-2.5 hover:bg-black/5" onClick={() => setSettings(!settings)}><Settings2 className="size-5"/></button></div></div>
      {settings && <div className={`absolute right-3 top-14 w-56 rounded-2xl border p-4 shadow-2xl ${night ? "border-white/10 bg-[#252525]" : "border-black/10 bg-white"}`}><div className="flex items-center justify-between"><span className="text-sm opacity-55">字号</span><div className="flex items-center gap-2"><button className="rounded-lg border border-current/15 p-1.5" onClick={() => changeFont(fontSize - 1)}><Minus className="size-3.5"/></button><span className="w-6 text-center text-sm">{fontSize}</span><button className="rounded-lg border border-current/15 p-1.5" onClick={() => changeFont(fontSize + 1)}><Plus className="size-3.5"/></button></div></div><button className="mt-4 flex w-full items-center justify-between text-sm" onClick={toggleNight}><span className="opacity-55">阅读主题</span><span className="flex items-center gap-1.5">{night ? <Moon className="size-4"/> : <Sun className="size-4"/>}{night ? "夜间" : "纸张"}</span></button></div>}
    </header>
    <main className="mx-auto min-h-screen max-w-[760px] px-5 pb-32 pt-12 sm:px-10 sm:pt-16"><p className="text-center text-xs uppercase tracking-[.2em] opacity-35">Chapter {chapter.number}</p><h1 className="mt-4 text-center font-serif text-3xl font-semibold leading-tight sm:text-4xl">第 {chapter.number} 章　{chapter.title}</h1><article className="mt-12 font-serif leading-[2.05] tracking-[.025em]" style={{ fontSize }}>{paragraphs.map((paragraph, index) => <p className="mb-[1.15em] indent-[2em]" key={index}>{paragraph}</p>)}</article><div className={`mt-20 grid grid-cols-2 gap-3 border-t pt-8 ${night ? "border-white/10" : "border-black/10"}`}><button disabled={number <= 1} className="btn-secondary border-current/15 bg-transparent disabled:opacity-25" onClick={() => setNumber(number - 1)}><ChevronLeft className="size-4"/>上一章</button><button disabled={number >= chapters.length} className="btn-primary" onClick={() => setNumber(number + 1)}>下一章<ChevronRight className="size-4"/></button><button className="btn-secondary col-span-2 border-current/15 bg-transparent" onClick={() => setCatalog(true)}><List className="size-4"/>查看目录</button></div></main>
    {catalog && <><button aria-label="关闭目录" className="fixed inset-0 z-30 bg-black/45" onClick={() => setCatalog(false)}/><aside className={`fixed inset-y-0 left-0 z-40 flex w-[88vw] max-w-sm flex-col shadow-2xl ${night ? "bg-[#202020]" : "bg-white"}`}><div className="flex items-center justify-between border-b border-current/10 p-5"><div><BookOpenText className="mb-3 size-5 text-ember"/><h2 className="line-clamp-1 font-serif text-xl font-semibold">{project.title}</h2><p className="mt-1 text-xs opacity-40">共 {chapters.length} 章</p></div><button className="p-2" onClick={() => setCatalog(false)}><X/></button></div><div className="flex-1 overflow-y-auto p-3">{chapters.map((item) => <button key={item.number} onClick={() => { setNumber(item.number); setCatalog(false); }} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm ${item.number === number ? "bg-ember/10 text-ember" : "hover:bg-black/5"}`}><span className="w-8 shrink-0 text-right text-xs opacity-40">{item.number}</span><span className="truncate">{item.title}</span></button>)}</div></aside></>}
  </div>;
}
