ALTER TABLE "NovelProject"
ADD COLUMN "protagonist" TEXT NOT NULL DEFAULT '',
ADD COLUMN "worldSetting" TEXT NOT NULL DEFAULT '',
ADD COLUMN "pace" TEXT NOT NULL DEFAULT '张弛有度',
ADD COLUMN "ending" TEXT NOT NULL DEFAULT '完整收束',
ADD COLUMN "constraints" TEXT NOT NULL DEFAULT '';
